const EDGE_COMMS = {
    "AA": "",
    "BA": "[R2 U' : [R2' , S]]",
    "DA": "[L2' U : [L2 , S']]",
    "EA": "[U' M U : [M' , U2]]",
    "FA": "[U : [R' E R , U2]]",
    "GA": "[U' : [L' E' L , U2']]",
    "HA": "[U : [R E' R' , U2]]",
    "JA": "[R' U : [S , R2]]",
    "KA": "[R' F' : [E , R U R']]",
    "LA": "[L U' : [S' , L2']]",
    "MA": "[U M U' : [M , U2]]",
    "NA": "[U' : [L' E L , U2']]",
    "OA": "[U : [R E R' , U2]]",
    "PA": "[U' : [L E' L' , U2']]",
    "QA": "",
    "RA": "[L' U : [L2 , S']]",
    "SA": "[U R' B R : [S , R2']]",
    "TA": "[R U' : [R2' , S]]",
    "UA": "[M' , U2]",
    "VA": "[U : [S , R2']]",
    "WA": "[U2 , M]",
    "XA": "[U' : [S' , L2]]",
    "AB": "[R2 U' : [S , R2']]",
    "BB": "",
    "DB": "[M2' U' : [M , U2]]",
    "EB": "[L F' L' , S']",
    "FB": "[R' E R , U']",
    "GB": "[U2' : [L' E' L , U']]",
    "HB": "[R E' R' , U']",
    "JB": "[E' : [R' E R , U']]",
    "KB": "[R : [U' R' U , M']]",
    "LB": "[R E2 R' , U']",
    "MB": "",
    "NB": "[U2' : [L' E L , U']]",
    "OB": "[R E R' , U']",
    "PB": "[U2' : [L E' L' , U']]",
    "QB": "[R' : [U' R U , M]]",
    "RB": "[R' E2 R , U']",
    "SB": "(M U' M' U')2",
    "TB": "[E : [R E' R' , U']]",
    "UB": "[L F' : [L' S' L , F2']]",
    "VB": "[R U R' : [S , R2]]",
    "WB": "[R : [U' R' U , M2']]",
    "XB": "L U L' U' L' U' L' U L U",
    "AD": "[L2' U : [S' , L2]]",
    "BD": "[M2' U : [M , U2']]",
    "DD": "",
    "ED": "",
    "FD": "[U2 : [R' E R , U]]",
    "GD": "[L' E' L , U]",
    "HD": "[U2 : [R E' R' , U]]",
    "JD": "[L' E2' L , U]",
    "KD": "[L' : [U L U' , M']]",
    "LD": "[U2 : [R E2 R' , U]]",
    "MD": "[R' F R , S]",
    "ND": "[L' E L , U]",
    "OD": "[U2 : [R E R' , U]]",
    "PD": "[L E' L' , U]",
    "QD": "[L : [U L' U' , M]]",
    "RD": "[U2 : [R' E2 R , U]]",
    "SD": "(M U M' U)2",
    "TD": "[L E2' L' , U]",
    "UD": "[R' F : [R S R' , F2]]",
    "VD": "R' U' R U R U R U R U' R' U'",
    "WD": "[l' M' : [U L U' , M2']]",
    "XD": "[L' U' L : [S' , L2]]",
    "AE": "[U' M U' : [M' , U2]]",
    "BE": "[S' , L F' L']",
    "DE": "",
    "EE": "",
    "FE": "[S : [R' E R , U']]",
    "GE": "[l' U L : [S' , L2']]",
    "HE": "[S : [R E' R' , U']]",
    "JE": "[M' : [R S' R' , U']]",
    "KE": "[l' : [U' L U , M']]",
    "LE": "[L' U' : [L S L' , U']]",
    "ME": "[M U' : [M' , U2]]",
    "NE": "[L' F' : [E , L2]]",
    "OE": "[R' F R' : [S , R2]]",
    "PE": "[R M U' : [M' , U2]]",
    "QE": "[l' : [U' L U , M]]",
    "RE": "[U' R F : [E' , R2']]",
    "SE": "M2' : (U' M U' M')2",
    "TE": "[l' : [E , L U' L']]",
    "UE": "[L' F' : [E' , L2]]",
    "VE": "[L2 : [S , L' F' L]]",
    "WE": "[l' : [U' L U , M2']]",
    "XE": "[S , L F' L']",
    "AF": "[U' : [R' E R , U2]]",
    "BF": "[U' , R' E R]",
    "DF": "[U' : [R' E R , U']]",
    "EF": "[S : [U' , R' E R]]",
    "FF": "",
    "GF": "[U S' U' , L]",
    "HF": "[M' U L' : [S' , L2']]",
    "JF": "[R U' R' , E]",
    "KF": "[M' : [U' L' U , M']]",
    "LF": "",
    "MF": "[M L' U' : [M' , U2']]",
    "NF": "[r U R : [E , R2']]",
    "OF": "[M' U R : [E , R2']]",
    "PF": "[U' E' L : [S' , L2']]",
    "QF": "[M' , U' L' U]",
    "RF": "[L U L' , E']",
    "SF": "[U' r' : [E , R U R']]",
    "TF": "[R2' : [R U' R' , E]]",
    "UF": "[U R' F' : [R S R' , F']]",
    "VF": "[U' E' R' : [E' , R2]]",
    "WF": "[M' : [U' L' U , M2']]",
    "XF": "[U E L' : [E' , L2]]",
    "AG": "[U : [L' E' L , U2']]",
    "BG": "[U : [L' E' L , U]]",
    "DG": "[U , L' E' L]",
    "EG": "[l' U L' : [S' , L2]]",
    "FG": "[L , U S' U']",
    "GG": "",
    "HG": "[L' , U S' U']",
    "JG": "[L' E2' : [L U L' , E]]",
    "KG": "[U : [S , L F L']]",
    "LG": "[L f' L : [S , L2']]",
    "MG": "[L F' L' : [S' , L2]]",
    "NG": "[L F' : [L2' , E]]",
    "OG": "[L F' L : [S , L2']]",
    "PG": "[M' U' L : [E' , L2']]",
    "QG": "[l' : [U' L' U , M]]",
    "RG": "[S' U' R : [E' , R2']]",
    "SG": "[U l : [E , L' U' L]]",
    "TG": "[L E2' : [L' U L , E']]",
    "UG": "[L F' : [E' , L2']]",
    "VG": "[S , L' F' L]",
    "WG": "[U : [L B' L' , S']]",
    "XG": "",
    "AH": "[U' : [R E' R' , U2]]",
    "BH": "[U' , R E' R']",
    "DH": "[U' : [R E' R' , U']]",
    "EH": "[S : [U' , R E' R']]",
    "FH": "[M' U L : [S' , L2']]",
    "GH": "[U S U' , L']",
    "HH": "",
    "JH": "[R2 : [R' U' R , E']]",
    "KH": "[M' : [U' L U , M']]",
    "LH": "[L' U L , E]",
    "MH": "[R F : [E' , R2']]",
    "NH": "[u R' : [S , R2]]",
    "OH": "[R' F : [E' , R2]]",
    "PH": "[l' U' L : [E' , L2']]",
    "QH": "[M' , U' L U]",
    "RH": "",
    "SH": "[U' M : [L S L' , U]]",
    "TH": "[R' U' R , E']",
    "UH": "[l' U : [L2 , S']]",
    "VH": "[u' R : [E , R2']]",
    "WH": "[M' : [U' L U , M2']]",
    "XH": "[u L : [E , L2']]",
    "AJ": "[R' U' : [S , R2']]",
    "BJ": "[E' : [U' , R' E R]]",
    "DJ": "[U , L' E2' L]",
    "EJ": "[M' : [U' , R S' R']]",
    "FJ": "[E , R U' R']",
    "GJ": "[L' E' : [L U L' , E']]",
    "HJ": "[R2 : [E' , R' U' R]]",
    "JJ": "",
    "KJ": "[U' R U , M']",
    "LJ": "[R' U' R' : [E , R2]]",
    "MJ": "[R U2' : [R' S' R , U']]",
    "NJ": "[E' , R U' R']",
    "OJ": "[R' f R : [S' , R2']]",
    "PJ": "",
    "QJ": "[U' R U , M]",
    "RJ": "[R' U' R : [E' , R2']]",
    "SJ": "[U2' : [U R U' , M]]",
    "TJ": "[U R : [S , R2']]",
    "UJ": "[U R U' : [M' , U2]]",
    "VJ": "U2 R U' R' U' R' U' R U R U'",
    "WJ": "[U' R U , M2']",
    "XJ": "[U L' : [E' , L2]]",
    "AK": "[R' F' : [R U R' , E]]",
    "BK": "[r : [U' R' U , M]]",
    "DK": "[l' : [U L U' , M]]",
    "EK": "[l' : [M' , U' L U]]",
    "FK": "[M2' : [U' L' U , M]]",
    "GK": "[U : [L F L' , S]]",
    "HK": "[M' : [M' , U' L U]]",
    "JK": "[M' , U' R U]",
    "KK": "",
    "LK": "[M' , U L' U']",
    "MK": "[r : [M' , U R' U']]",
    "NK": "[M2' : [U R' U' , M]]",
    "OK": "[U' : [R' F' R , S']]",
    "PK": "[M2' : [U R U' , M]]",
    "QK": "[U' : [R' F' R , S]",
    "RK": "[M' , U L U']",
    "SK": "U M U M' U2 M' U' M U",
    "TK": "[M' , U' R' U]",
    "UK": "",
    "VK": "[U R' F' R : [S , R2']]",
    "WK": "[D : [S' , R F R']]",
    "XK": "[U' L F L' : [S' , L2]]",
    "AL": "[L U : [S' , L2']]",
    "BL": "[U' , R E2 R']",
    "DL": "[U' : [R E2 R' , U']",
    "EL": "[L' U2 : [L S L' , U]]",
    "FL": "",
    "GL": "[L f' L' : [S , L2]]",
    "HL": "[E , L' U L]",
    "JL": "[R' U' R : [E , R2']]",
    "KL": "[U L' U' , M']",
    "LL": "",
    "ML": "[M' : [U , L' S L]]",
    "NL": "[L2' : [E , L U' L']]",
    "OL": "[R E : [R' U' R , E]]",
    "PL": "[E' , L' U L]",
    "QL": "[U L' U' , M]",
    "RL": "[U' L' : [S' , L2]]",
    "SL": "[U' R' B : [R2 , E]]",
    "TL": "[R U' R : [E , R2']]",
    "UL": "[U' D R : [E , R2']]",
    "VL": "[U' R : [E , R2']]",
    "WL": "[U L' U' , M2']]",
    "XL": "U2' L' U L U L U L' U' L' U",
    "AM": "[U M U : [M' , U2']]",
    "BM": "",
    "DM": "[S , R' F R]",
    "EM": "[M U : [M' , U2']]",
    "FM": "[M L' U : [M' , U2']]",
    "GM": "[L F' L : [S' , L2']]",
    "HM": "[R F : [R2' , E']]",
    "JM": "[R U : [R' S' R , U]]",
    "KM": "[r : [U R' U' , M']]",
    "LM": "[M' : [L' S L , U]]",
    "MM": "",
    "NM": "[S' : [L' E L , U]]",
    "OM": "[r U' R' : [S , R2]]",
    "PM": "[S' : [L E' L' , U]]",
    "QM": "[r : [U R' U' , M]]",
    "RM": "[M' : [R E' R' , U]]",
    "SM": "M2' : (U M U M')2",
    "TM": "[R u' R' : [E' , R2]]",
    "UM": "[R F : [E , R2']]",
    "VM": "[S' , R' F R]",
    "WM": "[r : [U R' U' , M2']]",
    "XM": "[R2' : [S' , R F R']]",
    "AN": "[U : [L' E L , U2']]",
    "BN": "[U : [L' E L , U]",
    "DN": "[U , L' E L]",
    "EN": "[L' F' : [E , L2]]",
    "FN": "[r U R' : [E , R2]]",
    "GN": "[L F' : [E , L2']]",
    "HN": "[u' L : [S' , L2']]",
    "JN": "[R U' R' , E']",
    "KN": "[M' : [U R' U' , M']]",
    "LN": "[L' : [U , L' E L]]",
    "MN": "[S' : [U , L' E L]]",
    "NN": "",
    "ON": "[U' S U , R]",
    "PN": "[M' U' R' : [S , R2]]",
    "QN": "[M' , U R' U']",
    "RN": "[L U L' , E]",
    "SN": "[U M : [R' S' R , U']]",
    "TN": "",
    "UN": "[r U' : [R2' , S]]",
    "VN": "[u' R' : [E' , R2]]",
    "WN": "[M' : [U R' U' , M2']]",
    "XN": "[u L' : [E' , L2]]",
    "AO": "[U' : [R E R' , U2]]",
    "BO": "[U' , R E R']",
    "DO": "[U' : [R E R' , U']]",
    "EO": "[R' F R : [S , R2']]",
    "FO": "[M' U R' : [E , R2]]",
    "GO": "[R' F R' : [S' , R2]]",
    "HO": "[R' F : [R2 , E']]",
    "JO": "[R' f R' : [S' , R2]]",
    "KO": "[U' : [S' , R' F' R]]",
    "LO": "[R E2 : [R' U' R , E']]",
    "MO": "[r U' R : [S , R2']]",
    "NO": "[R , U' S U]",
    "OO": "",
    "PO": "[R' , U' S U]",
    "QO": "[r : [U R U' , M]]",
    "RO": "[R' E2 : [R U' R' , E]]",
    "SO": "[U' r' : [E' , R U R']]",
    "TO": "[S U L' : [E , L2]]",
    "UO": "[R' F : [E , R2]]",
    "VO": "",
    "WO": "[U' : [R' B R , S]]",
    "XO": "[S' , R F R']",
    "AP": "[U : [L E' L' , U2']]",
    "BP": "[U : [L E' L' , U]",
    "DP": "[U , L E' L']",
    "EP": "[R M U : [M' , U2]]",
    "FP": "[U E R' : [S , R2]]",
    "GP": "[M' U' L' : [E' , L2]]",
    "HP": "[l' U' L' : [E' , L2]]",
    "JP": "",
    "KP": "[M' : [U R U' , M']]",
    "LP": "[L' U L , E']",
    "MP": "[S' : [U , L E' L']]",
    "NP": "[M' U' R : [S , R2']]",
    "OP": "[U' S U , R']",
    "PP": "",
    "QP": "[M' , U R U']",
    "RP": "[L2 : [L' U L , E']]",
    "SP": "[U l : [E' , L' U' L]]",
    "TP": "[R' U' R , E]",
    "UP": "[U' L F : [L' S' L , F]]",
    "VP": "[U' E' R : [E , R2']]",
    "WP": "[M' : [U R U' , M2']]",
    "XP": "[U E L : [E , L2']]",
    "AQ": "",
    "BQ": "[r' : [U' R U , M']]",
    "DQ": "[L : [M , U L' U']]",
    "EQ": "[L' : [U' L U , M']]",
    "FQ": "[U' L' U , M']",
    "GQ": "[L' : [U' L' U , M']]",
    "HQ": "[U' L U , M']",
    "JQ": "[M , U' R U]",
    "KQ": "[U' : [S , R' F' R]]",
    "LQ": "[M , U L' U']",
    "MQ": "[R : [U R' U' , M']]",
    "NQ": "[U R' U' , M']",
    "OQ": "[R : [U R U' , M']]",
    "PQ": "[U R U' , M']",
    "QQ": "",
    "RQ": "[M , U L U']",
    "SQ": "[U' : [S , R B R']]",
    "TQ": "[M , U' R' U]",
    "UQ": "[U : [R' F' R , S]",
    "VQ": "[r' : [U' R' U , M']]",
    "WQ": "[U : [R B R' , S]]",
    "XQ": "[l : [U L U' , M']]",
    "AR": "[L' U' : [L2 , S']]",
    "BR": "[U' , R' E2 R]",
    "DR": "[U' : [R E2 R' , U']",
    "ER": "[U' R F : [R2' , E']]",
    "FR": "[E' , L U L']",
    "GR": "[S' U' R' : [E' , R2]]",
    "HR": "",
    "JR": "[R' U' R' : [E' , R2]]",
    "KR": "[U L U' , M']",
    "LR": "[U' L : [S' , L2']]",
    "MR": "[M' : [U , R E' R']]",
    "NR": "[E , L U L']",
    "OR": "[R' E' : [R U' R' , E']]",
    "PR": "[L2 : [E' , L' U L]]",
    "QR": "[U L U' , M]",
    "RR": "",
    "SR": "[U2 : [U' L U , M]]",
    "TR": "[R U' R' : [E' , R2]]",
    "UR": "[U' L U : [M' , U2']]",
    "VR": "[U' R' : [E' , R2]]",
    "WR": "[U L U' , M2']",
    "XR": "L U' L' U' L' U' L U L U",
    "AS": "[U' R' B R : [S , R2']]",
    "BS": "(U M U M')2",
    "DS": "(U' M U' M')2",
    "ES": "M' : (U M' U M)2",
    "FS": "[U' r' : [R U R' , E]]",
    "GS": "[U l : [L' U' L , E]]",
    "HS": "[U' M : [U , L S L']]",
    "JS": "[U2 : [M , U R U']]",
    "KS": "U M' U' M U2 M U M' U",
    "LS": "[U' R' B : [E , R2]]",
    "MS": "M' : (U' M' U' M)2",
    "NS": "[U M : [U' , l' E l]]",
    "OS": "[U' r' : [R U R' , E']]",
    "PS": "[U l : [L' U' L , E']]",
    "QS": "[U' : [R B R' , S]]",
    "RS": "[U2' : [M , U' L U]]",
    "SS": "",
    "TS": "[U2 : [M , U R' U']]",
    "US": "[D' : [S' , R F R']]",
    "VS": "[U L B' L : [S , L2']]",
    "WS": "",
    "XS": "[U' R' B R' : [S' , R2]]",
    "AT": "[R U : [R2' , S]]",
    "BT": "[u' : [R E' R' , U]]",
    "DT": "[U , L E2' L']",
    "ET": "[M' : [U' , L' E L]]",
    "FT": "[R2' : [E , R U' R']]",
    "GT": "[L E : [L' U L , E]]",
    "HT": "[E' , R' U' R]",
    "JT": "[U R' : [S , R2]]",
    "KT": "[U' R' U , M']",
    "LT": "[R U' R' : [E , R2]]",
    "MT": "[U L' F' : [L2 , E]]",
    "NT": "",
    "OT": "[S U L : [E , L2']]",
    "PT": "[E , R' U' R]",
    "QT": "[U' R' U , M]",
    "RT": "[R U' R : [E' , R2']]",
    "ST": "[U2' : [U R' U' , M]]",
    "TT": "",
    "UT": "[U R' U' : [M' , U2]]",
    "VT": "R' U R U R U R' U' R' U'",
    "WT": "[U' R' U , M2']",
    "XT": "[U L : [E , L2']]",
    "AU": "[U2 , M']",
    "BU": "[L F : [L' S' L , F2']]",
    "DU": "[R' F' : [R S R' , F2]]",
    "EU": "[L' F' : [L2 , E']]",
    "FU": "[U R' F2 : [R S R' , F]]",
    "GU": "[L F' : [L2' , E']]",
    "HU": "[l' U : [S' , L2]]",
    "JU": "[D' U L : [E' , L2']]",
    "KU": "",
    "LU": "[U' D R' : [E , R2]]",
    "MU": "[R F : [R2' , E]]",
    "NU": "[r U' : [S , R2']]",
    "OU": "[R' F : [E , R2]]",
    "PU": "[U' L F2' : [L' S' L , F']]",
    "QU": "[U : [S , R' F' R]]",
    "RU": "[D U' R : [E' , R2']]",
    "SU": "[D' : [R F R' , S']]",
    "TU": "[U R' U : [M' , U2]]",
    "UU": "",
    "VU": "[R' F' : [R S' R' , F2]]",
    "WU": "M' U2 M' U2 M2'",
    "XU": "[L F : [L' S L , F2']]",
    "AV": "[U' : [S , R2']]",
    "BV": "[R' U R' : [S , R2]]",
    "DV": "U R U R' U' R' U' R' U R",
    "EV": "[L2 : [L' F' L , S]]",
    "FV": "[U' E' R : [E' , R2']]",
    "GV": "[L' F' L , S]",
    "HV": "[u' R' : [E , R2]]",
    "JV": "U R' U' R' U R U R U R' U2",
    "KV": "[U R' F' R' : [S , R2]]",
    "LV": "[U' R' : [E , R2]]",
    "MV": "[R' F R , S']",
    "NV": "[u' R : [E' , R2']]",
    "OV": "",
    "PV": "[U' E' R' : [E , R2]]",
    "QV": "[R' : [U' R' U , M]]",
    "RV": "[U' R : [E' , R2']]",
    "SV": "[U L B' L' : [S , L2]]",
    "TV": "U R U R U' R' U' R' U' R",
    "UV": "[R' F : [R S' R' , F2]]",
    "VV": "",
    "WV": "[D' R' F' : [R S' R' , F2]]",
    "XV": "[U' : [R2' , S']]",
    "AW": "[M , U2]",
    "BW": "[r M' : [U' R' U , M2']]",
    "DW": "[l' M' : [U L U' , M2']]",
    "EW": "[L' M : [U' L U , M2']]",
    "FW": "[M : [U' L' U , M2']]",
    "GW": "[U : [S' , L B' L']]",
    "HW": "[M : [U' L U , M2']]",
    "JW": "[M2' , U' R U]",
    "KW": "[D : [R F R' , S']]",
    "LW": "[M2' , U L' U']",
    "MW": "[R M : [U R' U' , M2']]",
    "NW": "[M : [U R' U' , M2']]",
    "OW": "[U' : [S , R' B R]]",
    "PW": "[M : [U R U' , M2']]",
    "QW": "[U : [S , R B R']]",
    "RW": "[M2 , U L U']",
    "SW": "",
    "TW": "[M2' , U' R' U]",
    "UW": "u2 M' u2 M'",
    "VW": "[D' R' F : [R S' R' , F2]]",
    "WW": "",
    "XW": "[D L F' : [L' S L , F2']]",
    "AX": "[U : [S' , L2']]",
    "BX": "U' L' U' L U L U L U' L'",
    "DX": "[L U' L : [S' , L2']]",
    "EX": "[L F' L' , S]]",
    "FX": "[U E L : [E' , L2']]",
    "GX": "",
    "HX": "[u L' : [E , L2]]",
    "JX": "[U L : [E' , L2']]",
    "KX": "[U' L F L : [S' , L2']]",
    "LX": "U' L U L U' L' U' L' U' L U2'",
    "MX": "[R2' : [R F R' , S']]",
    "NX": "[u L : [E' , L2']]",
    "OX": "[R F R' , S']]",
    "PX": "[U E L' : [E , L2]]",
    "QX": "[L : [U L U' , M]]",
    "RX": "U' L' U' L' U L U L U L'",
    "SX": "[U' R' B R : [S' , R2']]",
    "TX": "[U L' : [E , L2]]",
    "UX": "[L F' : [L' S L , F2']]",
    "VX": "[U' : [S' , R2']]",
    "WX": "[D L F : [L' S L , F2']]",
    "XX": ""
};
const EDGE_TYPES = {
    "AA": "",
    "BA": "4-Mover",
    "DA": "4-Mover",
    "EA": "4-Mover",
    "FA": "U-Swap",
    "GA": "U-Swap",
    "HA": "U-Swap",
    "JA": "4-Mover",
    "KA": "E-Swap",
    "LA": "4-Mover",
    "MA": "4-Mover",
    "NA": "U-Swap",
    "OA": "U-Swap",
    "PA": "U-Swap",
    "QA": "",
    "RA": "4-Mover",
    "SA": "4-Mover",
    "TA": "4-Mover",
    "UA": "4-Mover",
    "VA": "4-Mover",
    "WA": "4-Mover",
    "XA": "4-Mover",
    "AB": "4-Mover",
    "BB": "",
    "DB": "4-Mover",
    "EB": "S-Swap",
    "FB": "U-Swap",
    "GB": "U-Swap",
    "HB": "U-Swap",
    "JB": "U-Swap",
    "KB": "M-Swap",
    "LB": "U-Swap",
    "MB": "",
    "NB": "U-Swap",
    "OB": "U-Swap",
    "PB": "U-Swap",
    "QB": "M-Swap",
    "RB": "U-Swap",
    "SB": "Alg",
    "TB": "U-Swap",
    "UB": "F-Swap",
    "VB": "4-Mover",
    "WB": "M-Swap",
    "XB": "Alg",
    "AD": "4-Mover",
    "BD": "4-Mover",
    "DD": "",
    "ED": "",
    "FD": "U-Swap",
    "GD": "U-Swap",
    "HD": "U-Swap",
    "JD": "U-Swap",
    "KD": "M-Swap",
    "LD": "U-Swap",
    "MD": "S-Swap",
    "ND": "U-Swap",
    "OD": "U-Swap",
    "PD": "U-Swap",
    "QD": "M-Swap",
    "RD": "U-Swap",
    "SD": "Alg",
    "TD": "U-Swap",
    "UD": "F-Swap",
    "VD": "Alg",
    "WD": "M-Swap",
    "XD": "4-Mover",
    "AE": "4-Mover",
    "BE": "S-Swap",
    "DE": "",
    "EE": "",
    "FE": "U-Swap",
    "GE": "4-Mover",
    "HE": "U-Swap",
    "JE": "U-Swap",
    "KE": "M-Swap",
    "LE": "U-Swap",
    "ME": "4-Mover",
    "NE": "4-Mover",
    "OE": "4-Mover",
    "PE": "4-Mover",
    "QE": "M-Swap",
    "RE": "4-Mover",
    "SE": "Alg",
    "TE": "E-Swap",
    "UE": "4-Mover",
    "VE": "S-Swap",
    "WE": "M-Swap",
    "XE": "S-Swap",
    "AF": "U-Swap",
    "BF": "U-Swap",
    "DF": "U-Swap",
    "EF": "U-Swap",
    "FF": "",
    "GF": "S-Insert",
    "HF": "4-Mover",
    "JF": "E-Swap",
    "KF": "M-Swap",
    "LF": "",
    "MF": "4-Mover",
    "NF": "4-Mover",
    "OF": "4-Mover",
    "PF": "4-Mover",
    "QF": "M-Swap",
    "RF": "E-Swap",
    "SF": "E-Swap",
    "TF": "E-Swap",
    "UF": "F-Swap",
    "VF": "4-Mover",
    "WF": "M-Swap",
    "XF": "4-Mover",
    "AG": "U-Swap",
    "BG": "U-Swap",
    "DG": "U-Swap",
    "EG": "4-Mover",
    "FG": "S-Insert",
    "GG": "",
    "HG": "S-Insert",
    "JG": "E-Swap",
    "KG": "S-Swap",
    "LG": "4-Mover",
    "MG": "4-Mover",
    "NG": "4-Mover",
    "OG": "4-Mover",
    "PG": "4-Mover",
    "QG": "M-Swap",
    "RG": "4-Mover",
    "SG": "E-Swap",
    "TG": "E-Swap",
    "UG": "4-Mover",
    "VG": "S-Swap",
    "WG": "S-Swap",
    "XG": "",
    "AH": "U-Swap",
    "BH": "U-Swap",
    "DH": "U-Swap",
    "EH": "U-Swap",
    "FH": "4-Mover",
    "GH": "S-Insert",
    "HH": "",
    "JH": "E-Swap",
    "KH": "M-Swap",
    "LH": "E-Swap",
    "MH": "4-Mover",
    "NH": "4-Mover",
    "OH": "4-Mover",
    "PH": "4-Mover",
    "QH": "M-Swap",
    "RH": "",
    "SH": "U-Swap",
    "TH": "E-Swap",
    "UH": "4-Mover",
    "VH": "4-Mover",
    "WH": "M-Swap",
    "XH": "4-Mover",
    "AJ": "4-Mover",
    "BJ": "U-Swap",
    "DJ": "U-Swap",
    "EJ": "U-Swap",
    "FJ": "E-Swap",
    "GJ": "E-Swap",
    "HJ": "E-Swap",
    "JJ": "",
    "KJ": "M-Swap",
    "LJ": "4-Mover",
    "MJ": "U-Swap",
    "NJ": "E-Swap",
    "OJ": "4-Mover",
    "PJ": "",
    "QJ": "M-Swap",
    "RJ": "4-Mover",
    "SJ": "M-Swap",
    "TJ": "4-Mover",
    "UJ": "4-Mover",
    "VJ": "Alg",
    "WJ": "M-Swap",
    "XJ": "4-Mover",
    "AK": "E-Swap",
    "BK": "M-Swap",
    "DK": "M-Swap",
    "EK": "M-Swap",
    "FK": "M-Swap",
    "GK": "S-Swap",
    "HK": "M-Swap",
    "JK": "M-Swap",
    "KK": "",
    "LK": "M-Swap",
    "MK": "M-Swap",
    "NK": "M-Swap",
    "OK": "S-Swap",
    "PK": "M-Swap",
    "QK": "S-Swap",
    "RK": "M-Swap",
    "SK": "Alg",
    "TK": "M-Swap",
    "UK": "",
    "VK": "4-Mover",
    "WK": "S-Swap",
    "XK": "4-Mover",
    "AL": "4-Mover",
    "BL": "U-Swap",
    "DL": "U-Swap",
    "EL": "U-Swap",
    "FL": "",
    "GL": "4-Mover",
    "HL": "E-Swap",
    "JL": "4-Mover",
    "KL": "M-Swap",
    "LL": "",
    "ML": "U-Swap",
    "NL": "E-Swap",
    "OL": "E-Swap",
    "PL": "E-Swap",
    "QL": "M-Swap",
    "RL": "4-Mover",
    "SL": "4-Mover",
    "TL": "4-Mover",
    "UL": "4-Mover",
    "VL": "4-Mover",
    "WL": "M-Swap",
    "XL": "Alg",
    "AM": "4-Mover",
    "BM": "",
    "DM": "S-Swap",
    "EM": "4-Mover",
    "FM": "4-Mover",
    "GM": "4-Mover",
    "HM": "4-Mover",
    "JM": "U-Swap",
    "KM": "M-Swap",
    "LM": "U-Swap",
    "MM": "",
    "NM": "U-Swap",
    "OM": "4-Mover",
    "PM": "U-Swap",
    "QM": "M-Swap",
    "RM": "U-Swap",
    "SM": "Alg",
    "TM": "4-Mover",
    "UM": "4-Mover",
    "VM": "S-Swap",
    "WM": "M-Swap",
    "XM": "S-Swap",
    "AN": "U-Swap",
    "BN": "U-Swap",
    "DN": "U-Swap",
    "EN": "4-Mover",
    "FN": "4-Mover",
    "GN": "4-Mover",
    "HN": "4-Mover",
    "JN": "E-Swap",
    "KN": "M-Swap",
    "LN": "U-Swap",
    "MN": "U-Swap",
    "NN": "",
    "ON": "S-Insert",
    "PN": "4-Mover",
    "QN": "M-Swap",
    "RN": "E-Swap",
    "SN": "U-Swap",
    "TN": "",
    "UN": "4-Mover",
    "VN": "4-Mover",
    "WN": "M-Swap",
    "XN": "4-Mover",
    "AO": "U-Swap",
    "BO": "U-Swap",
    "DO": "U-Swap",
    "EO": "4-Mover",
    "FO": "4-Mover",
    "GO": "4-Mover",
    "HO": "4-Mover",
    "JO": "4-Mover",
    "KO": "S-Swap",
    "LO": "E-Swap",
    "MO": "4-Mover",
    "NO": "S-Insert",
    "OO": "",
    "PO": "S-Insert",
    "QO": "M-Swap",
    "RO": "E-Swap",
    "SO": "E-Swap",
    "TO": "4-Mover",
    "UO": "4-Mover",
    "VO": "",
    "WO": "S-Swap",
    "XO": "S-Swap",
    "AP": "U-Swap",
    "BP": "U-Swap",
    "DP": "U-Swap",
    "EP": "4-Mover",
    "FP": "4-Mover",
    "GP": "4-Mover",
    "HP": "4-Mover",
    "JP": "",
    "KP": "M-Swap",
    "LP": "E-Swap",
    "MP": "U-Swap",
    "NP": "4-Mover",
    "OP": "S-Insert",
    "PP": "",
    "QP": "M-Swap",
    "RP": "E-Swap",
    "SP": "E-Swap",
    "TP": "E-Swap",
    "UP": "F-Swap",
    "VP": "4-Mover",
    "WP": "M-Swap",
    "XP": "4-Mover",
    "AQ": "",
    "BQ": "M-Swap",
    "DQ": "M-Swap",
    "EQ": "M-Swap",
    "FQ": "M-Swap",
    "GQ": "M-Swap",
    "HQ": "M-Swap",
    "JQ": "M-Swap",
    "KQ": "S-Swap",
    "LQ": "M-Swap",
    "MQ": "M-Swap",
    "NQ": "M-Swap",
    "OQ": "M-Swap",
    "PQ": "M-Swap",
    "QQ": "",
    "RQ": "M-Swap",
    "SQ": "S-Swap",
    "TQ": "M-Swap",
    "UQ": "S-Swap",
    "VQ": "M-Swap",
    "WQ": "S-Swap",
    "XQ": "M-Swap",
    "AR": "4-Mover",
    "BR": "U-Swap",
    "DR": "U-Swap",
    "ER": "4-Mover",
    "FR": "E-Swap",
    "GR": "4-Mover",
    "HR": "",
    "JR": "4-Mover",
    "KR": "M-Swap",
    "LR": "4-Mover",
    "MR": "U-Swap",
    "NR": "E-Swap",
    "OR": "E-Swap",
    "PR": "E-Swap",
    "QR": "M-Swap",
    "RR": "",
    "SR": "M-Swap",
    "TR": "4-Mover",
    "UR": "4-Mover",
    "VR": "4-Mover",
    "WR": "M-Swap",
    "XR": "Alg",
    "AS": "4-Mover",
    "BS": "Alg",
    "DS": "Alg",
    "ES": "Alg",
    "FS": "E-Swap",
    "GS": "E-Swap",
    "HS": "U-Swap",
    "JS": "M-Swap",
    "KS": "Alg",
    "LS": "4-Mover",
    "MS": "Alg",
    "NS": "U-Swap",
    "OS": "E-Swap",
    "PS": "E-Swap",
    "QS": "S-Swap",
    "RS": "M-Swap",
    "SS": "",
    "TS": "M-Swap",
    "US": "S-Swap",
    "VS": "4-Mover",
    "WS": "",
    "XS": "4-Mover",
    "AT": "4-Mover",
    "BT": "U-Swap",
    "DT": "U-Swap",
    "ET": "U-Swap",
    "FT": "E-Swap",
    "GT": "E-Swap",
    "HT": "E-Swap",
    "JT": "4-Mover",
    "KT": "M-Swap",
    "LT": "4-Mover",
    "MT": "4-Mover",
    "NT": "",
    "OT": "4-Mover",
    "PT": "E-Swap",
    "QT": "M-Swap",
    "RT": "4-Mover",
    "ST": "M-Swap",
    "TT": "",
    "UT": "4-Mover",
    "VT": "Alg",
    "WT": "M-Swap",
    "XT": "4-Mover",
    "AU": "4-Mover",
    "BU": "F-Swap",
    "DU": "F-Swap",
    "EU": "4-Mover",
    "FU": "F-Swap",
    "GU": "4-Mover",
    "HU": "4-Mover",
    "JU": "4-Mover",
    "KU": "",
    "LU": "4-Mover",
    "MU": "4-Mover",
    "NU": "4-Mover",
    "OU": "4-Mover",
    "PU": "F-Swap",
    "QU": "S-Swap",
    "RU": "4-Mover",
    "SU": "S-Swap",
    "TU": "4-Mover",
    "UU": "",
    "VU": "F-Swap",
    "WU": "Alg",
    "XU": "F-Swap",
    "AV": "4-Mover",
    "BV": "4-Mover",
    "DV": "Alg",
    "EV": "S-Swap",
    "FV": "4-Mover",
    "GV": "S-Swap",
    "HV": "4-Mover",
    "JV": "Alg",
    "KV": "4-Mover",
    "LV": "4-Mover",
    "MV": "S-Swap",
    "NV": "4-Mover",
    "OV": "",
    "PV": "4-Mover",
    "QV": "M-Swap",
    "RV": "4-Mover",
    "SV": "4-Mover",
    "TV": "Alg",
    "UV": "F-Swap",
    "VV": "",
    "WV": "F-Swap",
    "XV": "4-Mover",
    "AW": "4-Mover",
    "BW": "M-Swap",
    "DW": "M-Swap",
    "EW": "M-Swap",
    "FW": "M-Swap",
    "GW": "S-Swap",
    "HW": "M-Swap",
    "JW": "M-Swap",
    "KW": "S-Swap",
    "LW": "M-Swap",
    "MW": "M-Swap",
    "NW": "M-Swap",
    "OW": "S-Swap",
    "PW": "M-Swap",
    "QW": "S-Swap",
    "RW": "M-Swap",
    "SW": "",
    "TW": "M-Swap",
    "UW": "Alg",
    "VW": "F-Swap",
    "WW": "",
    "XW": "F-Swap",
    "AX": "4-Mover",
    "BX": "Alg",
    "DX": "4-Mover",
    "EX": "S-Swap",
    "FX": "4-Mover",
    "GX": "",
    "HX": "4-Mover",
    "JX": "4-Mover",
    "KX": "4-Mover",
    "LX": "Alg",
    "MX": "S-Swap",
    "NX": "4-Mover",
    "OX": "S-Swap",
    "PX": "4-Mover",
    "QX": "M-Swap",
    "RX": "Alg",
    "SX": "4-Mover",
    "TX": "4-Mover",
    "UX": "F-Swap",
    "VX": "4-Mover",
    "WX": "F-Swap",
    "XX": ""
};
const CORNER_COMMS = {
    "AA": "",
    "BA": "[R' B' R : [U' , R D R']]",
    "DA": "[R' D R U' : [R' D' R , U']]",
    "EA": "",
    "FA": "[F : [R' D' R , U2]]",
    "GA": "[U2 , R' D R]",
    "HA": "[U : [R D' R' , U2]]",
    "IA": "R' D R U' R : [F , R' U R U']",
    "KA": "[U D : [R D R' , U2]]",
    "LA": "[D' U : [R D' R' , U2]]",
    "NA": "[R' U D R : [D' , R U' R']]",
    "OA": "[U : [R D R' , U2]]",
    "PA": "[U2 , R' D' R]",
    "QA": "[R' U' D : [R D R' , U2]]",
    "RA": "",
    "SA": "[U D' : [R D R' , U2]]",
    "TA": "[U D : [R D' R' , U2]]",
    "UA": "[R F' R' U : [R D R' , U2]]",
    "VA": "[U2 , R' D R U' R D' R']",
    "WA": "[R D' R' : [U2 , R' D R]]",
    "XA": "[R' U' D' R : [D , R U' R']]",
    "AB": "[R' B' R : [R D R' , U']]",
    "BB": "",
    "DB": "[R F' R' : [U , R' D R]]",
    "EB": "[R2 : [D , R' U R]]",
    "FB": "[R' : [U' , R' D' R]]",
    "GB": "[U , R' D R]",
    "HB": "[R D' R' , U']",
    "IB": "[R2 U' : [R U R' , D']]",
    "KB": "[D' : [U , R' D R]]",
    "LB": "[D : [U , R' D' R]]",
    "NB": "",
    "OB": "[R D R' , U']",
    "PB": "[U , R' D' R]",
    "QB": "",
    "RB": "[R2 U : [D , R' U' R]]",
    "SB": "[D' : [R D R' , U']]",
    "TB": "[D : [R D' R' , U']]",
    "UB": "[R F' : [D , R' U' R]]",
    "VB": "[U , R' D R U' R D' R']",
    "WB": "[R D' R' U R' D R , U']",
    "XB": "[R' B : [R U R' , D']]",
    "AD": "[R' D R U2 : [R' D' R , U]]",
    "BD": "[R F' R' : [R' D R, U]]",
    "DD": "",
    "ED": "[U' R : [U2 , R D R']]",
    "FD": "",
    "GD": "[U' , R' D R]",
    "HD": "[U2 : [R D' R' , U]]",
    "ID": "",
    "KD": "[D' : [U' , R' D R]]",
    "LD": "[D : [U' , R' D' R]]",
    "ND": "[U' R2' : [D' , R U2 R']]",
    "OD": "[U2 : [R D R' , U]]",
    "PD": "[U' , R' D' R]",
    "QD": "[R' D' : [R' D R , U']]",
    "RD": "[U' R2' : [D' , R U' R']]",
    "SD": "[D : [U' , R' D R]]",
    "TD": "[D' : [U' , R' D' R]]",
    "UD": "[U' : [F2' , U R' U' R]]",
    "VD": "[U' , R' D R U' R D' R']",
    "WD": "[R D' R' : [U' , R' D R]]",
    "XD": "[R' D' R : [D , R U' R']]",
    "AE": "",
    "BE": "[R : [U , R D R']]",
    "DE": "[U' R2 : [D , R' U2 R]]",
    "EE": "",
    "FE": "[U' R' U , L]",
    "GE": "[U R' : [R' D R , U']]",
    "HE": "[R D' : [U , R D R']]",
    "IE": "[l' U' : [R D' R' , U2]]",
    "KE": "[D' U R' : [R' D R , U']]",
    "LE": "[R U2 : [R' D R , U']]",
    "NE": "[R : [U , R2 D R2 D' R2]]",
    "OE": "[U' R' F R : [R D R' , U']]",
    "PE": "[U R' U' : [R D R' , U']]",
    "QE": "[F' L F , R']",
    "RE": "",
    "SE": "[D U R' : [R' D R , U']]",
    "TE": "[R U2 : [R' D' R , U']]",
    "UE": "[D' R : [U , R D' R']]",
    "VE": "[U R' D' : [R' D' R , U']]",
    "WE": "[D R : [U , R D' R']]",
    "XE": "[R : [U , R D' R']]",
    "AF": "[F : [U2 , F' R F R']]",
    "BF": "[R2 : [D' , R U' R']]",
    "DF": "",
    "EF": "[U' R' F : [D , R U R']]",
    "FF": "",
    "GF": "[R' U' : [R U R' , D]]",
    "HF": "[U' R U' : [R' U R , D']]",
    "IF": "",
    "KF": "[U R U' : [F , U R' U' R]]",
    "LF": "[D R' U' : [R U R' , D']]",
    "NF": "[R U' D' R' : [R' U R , D]]",
    "OF": "[D' R : [R' U R U' , F]]",
    "PF": "[R' U' : [R U R' , D']]",
    "QF": "[R' F : [D , R U R']]",
    "RF": "[F , l U' l']",
    "SF": "[F , l U2 l']",
    "TF": "[D' R' U' : [R U R' , D']]",
    "UF": "[U' R' U : [D , R U' R']]",
    "VF": "[U' D' R' U : [D , R U' R']]",
    "WF": "[R U' R2' : [U , R D R']]",
    "XF": "[U' D R' U : [D , R U' R']]",
    "AG": "[R' D R , U2]",
    "BG": "[R' D R , U]",
    "DG": "[R' D R , U']",
    "EG": "[U R' : [U' , R' D R]]",
    "FG": "[R' U' : [D , R U R']]",
    "GG": "",
    "HG": "[R' D : [F' , D' R D R']]",
    "IG": "[R' D : [F2 , D' R D R']]",
    "KG": "[U : [R U' R' , D]]",
    "LG": "",
    "NG": "[U R U' : [R' D R , U2]]",
    "OG": "[U D' : [R U' R' , D2]]",
    "PG": "[U R' D' : [R U' R' , D2]]",
    "QG": "[R' U : [D , R U' R']]",
    "RG": "[R B' R' : [U , R' D R]]",
    "SG": "[U D2 : [R U' R' , D']]",
    "TG": "[R' D R2 : [U , R' D' R]]",
    "UG": "",
    "VG": "[U D R D' : [R' D R , U']]",
    "WG": "[U R2 : [U' , R' D R]]",
    "XG": "[D R : [F2 , R' U R U']]",
    "AH": "[U' : [R D' R' , U2]]",
    "BH": "[U' , R D' R']",
    "DH": "[U' : [R D' R' , U']]",
    "EH": "[R D' : [R D R' , U]]",
    "FH": "[U' R U' : [D' , R' U R]]",
    "GH": "[D R' : [F' , R D' R']]",
    "HH": "",
    "IH": "[R U D : [R' D R , U2]]",
    "KH": "[l' U : [R U' R' , D]]",
    "LH": "[D : [R U R' , D]]",
    "NH": "[U R : [U2 , R D' R']]",
    "OH": "[R D : [R' U' R , D2]]",
    "PH": "[R U R' , D2]",
    "QH": "[R , U' L U]",
    "RH": "[U D R' F' : [R U' R' , D]]",
    "SH": "",
    "TH": "[D' : [R U R' , D']]",
    "UH": "[D R U' R' : [U2 , R' D R]]",
    "VH": "[R U' D R' : [U2 , R' D R]]",
    "WH": "[R D' R' : [U , R' D R]]",
    "XH": "",
    "AI": "[l' D' U : [R D R' , U2]]",
    "BI": "[R2 U' : [D' , R U R']]",
    "DI": "",
    "EI": "[l' U : [R D' R' , U2]]",
    "FI": "",
    "GI": "[D R' : [F2 , R D' R' D]]",
    "HI": "[R U' D : [R' D R , U2]]",
    "II": "",
    "KI": "[R' : [F2 , R D' R' D]]",
    "LI": "[R U' : [R' D R , U U]]",
    "NI": "[R' F' R D U : [R' D' R , U2]",
    "OI": "[R D' U' : [R' D R , U2]]",
    "PI": "[D R U' : [R' D' R , U2]]",
    "QI": "[R D' U' : [R' D' R , U2]]",
    "RI": "[R U R' D' : [R' D R , U2]]",
    "SI": "[D R' D : [F2 , D' R D R']]",
    "TI": "[R U' : [R' D' R , U2]]",
    "UI": "[R D U' : [R' D' R , U2]]",
    "VI": "[R U' R' U D : [R D R' , U2]]",
    "WI": "[D R : [U2 , R D' R']]",
    "XI": "[R2 U : [R' U R , D']]",
    "AK": "[D U' : [R D R' , U2]]",
    "BK": "[D' : [R' D R , U]]",
    "DK": "[D' : [R' D R , U']]",
    "EK": "[U D' R' : [U' , R' D R]]",
    "FK": "[R : [F , R' U R U']]",
    "GK": "[U : [D , R U' R']]",
    "HK": "[l' U : [D , R U' R']]",
    "IK": "[D' R' D : [F2 , D' R D R']]",
    "KK": "",
    "LK": "[D' R' D : [F' , D' R D R']]",
    "NK": "[U' R' U' : [R D R' , U2]]",
    "OK": "[U : [D' , R U' R']]",
    "PK": "",
    "QK": "[D' R' U : [D , R U' R']]",
    "RK": "[U' R' U' : [R D R' , U']]",
    "SK": "[U : [D2 , R U' R']]",
    "TK": "[R U R' U' : [R U R' , D']]",
    "UK": "[R : [F2 , R' U R U']]",
    "VK": "",
    "WK": "[U R D' : [R' D R , U']]",
    "XK": "[R' D' R : [D ,R U R']]",
    "AL": "[D : [R' D' R , U2]]",
    "BL": "[D : [R' D' R , U]]",
    "DL": "[D : [R' D' R , U']]",
    "EL": "[R U : [R' D R , U]]",
    "FL": "[D R' U' : [D' , R U R']]",
    "GL": "",
    "HL": "[D2 : [R U R' , D']]",
    "IL": "[R U : [R' D R , U2]]",
    "KL": "[R' : [F' , R D' R' D]]",
    "LL": "",
    "NL": "[U R U' D : [R' D' R , U2]]",
    "OL": "[R D : [R' U' R , D]]",
    "PL": "[R U R' , D]",
    "QL": "[R' F : [D , R U' R']]",
    "RL": "[D R' : [R' U R , D]]",
    "SL": "[D' R D : [R' U' R , D2]]",
    "TL": "[D' : [R U R' , D2]]",
    "UL": "",
    "VL": "[R U' R' : [U2 , R' D R]]",
    "WL": "[D' R2 : [R' U' R , D']]",
    "XL": "[D R D : [R' D' R , U]]",
    "AN": "[R' U D R2 : [U' , R' D' R]]",
    "BN": "",
    "DN": "[U' R' : [U2 , R' D' R]]",
    "EN": "[R' D R2 D' R2' : [U , R2 D R2' D' R2]]",
    "FN": "[R U' D' R' : [D , R' U R]]",
    "GN": "[U R U : [R' D R , U2]]",
    "HN": "[U R : [R D' R' , U2]]",
    "IN": "[R' F' R D U : [U2 , R' D' R]",
    "KN": "[U' R' U : [R D R' , U2]]",
    "LN": "[U R U D : [R' D' R , U2]]",
    "NN": "",
    "ON": "[U R U : [R' D' R , U2]]",
    "PN": "[U' R' D U : [R D' R' , U2]]",
    "QN": "",
    "RN": "[U R2 U' : [R U R' , D']]",
    "SN": "[U' R' U : [R D' R' , U2]]",
    "TN": "[R' F' R D' U' : [R' D R , U2]]",
    "UN": "[U' R' : [U2 , R' D R]]",
    "VN": "[U' D' R' : [U2 , R' D R]]",
    "WN": "[U R U D' : [R' D R , U2]]",
    "XN": "[D U' R' : [U2 , R' D R]]",
    "AO": "[U' : [R D R' , U2]]",
    "BO": "[U' , R D R']",
    "DO": "[U' : [R D R' , U']]",
    "EO": "[U' R : [R U' R' , D']]",
    "FO": "[D' R : [F , R' U R U']]",
    "GO": "[U D : [R U' R' , D2]]",
    "HO": "[R D' : [R' U' R , D2]]",
    "IO": "[R D' U : [R' D R , U2]]",
    "KO": "[U : [R U' R' , D']]",
    "LO": "[R D2 : [R' U' R , D']]",
    "NO": "[U R U' : [R' D' R , U2]]",
    "OO": "",
    "PO": "[R D' : [U , R' D R]]",
    "QO": "[U' R U : [D , R' U' R]]",
    "RO": "[R B' : [D , R' U' R]]",
    "SO": "[U' : [D' , R' U' R]]",
    "TO": "",
    "UO": "[U' R' : [U , R' D R]]",
    "VO": "[D' R : [F2 , R' U R U']]",
    "WO": "",
    "XO": "[U D' R D' : [R' D R , U']]",
    "AP": "[R' D' R , U2]",
    "BP": "[R' D' R , U]",
    "DP": "[R' D' R , U']",
    "EP": "[U R' U2 : [R D R' , U]]",
    "FP": "[R' U' : [D' , R U R']]",
    "GP": "[U R' D : [R U' R' , D2]]",
    "HP": "[D2 , R U R']",
    "IP": "[D R U : [R' D' R , U2]]",
    "KP": "",
    "LP": "[D , R U R']",
    "NP": "[U' R' D U' : [R D' R' , U2]]",
    "OP": "[R D' : [R' D R , U]]",
    "PP": "",
    "QP": "[R' U : [D' , R U' R']]",
    "RP": "[R2' : [U , R D R']]",
    "SP": "[U R' D' : [D' , R U' R']]",
    "TP": "[D' , R U R']",
    "UP": "[R D : [R' D' R , U]]",
    "VP": "",
    "WP": "[D' R U' R' : [U2 , R' D R]]",
    "XP": "[R2 : [R' U' R , D']]",
    "AQ": "[R' U D : [R D R' , U2]]",
    "BQ": "",
    "DQ": "[R' D' : [U' , R' D R]]",
    "EQ": "[R' , F' L F]]",
    "FQ": "[R' F : [R U R' , D]]",
    "GQ": "[R' U : [R U' R' , D]]",
    "HQ": "[U' L U , R]",
    "IQ": "[R U D' : [R' D' R , U2]]",
    "KQ": "[D' R' U : [R U' R' , D]]",
    "LQ": "[R' F : [R U' R' , D]]",
    "NQ": "",
    "OQ": "[U' R U : [R' U' R , D]]",
    "PQ": "[R' U : [R U' R' , D']]",
    "QQ": "",
    "RQ": "[U' L' U , R]",
    "SQ": "[D R' U : [R U' R' , D]]",
    "TQ": "[R U' : [D , R' U R]]",
    "UQ": "[D' R U' : [D' , R' U R]]",
    "VQ": "[U R' U' : [D' , R U R']]",
    "WQ": "[D R U' : [D' , R' U R]]",
    "XQ": "[R U' : [D' , R' U R]]",
    "AR": "",
    "BR": "[R2 U : [R' U' R , D]]",
    "DR": "[U' R' : [U' , R' D' R]]",
    "ER": "",
    "FR": "[l U' l' , F]",
    "GR": "[R B' R' : [R' D R , U]]",
    "HR": "[U D R' F' : [D , R U' R']]",
    "IR": "[R U R' U D : [R D R' , U2]]",
    "KR": "[U' R' U2 : [R D R' , U]]",
    "LR": "[D R' : [D , R' U R]]",
    "NR": "[U R2 U' : [D' , R U R']]",
    "OR": "[R B' : [R' U' R , D]]",
    "PR": "[R' : [D , R' U R]]",
    "QR": "[R , U' L' U]",
    "RR": "",
    "SR": "[U' R' U2 : [R D' R' , U]]",
    "TR": "[D' R' : [D , R' U R]]",
    "UR": "[U' R' : [U' , R' D R]]",
    "VR": "[D' U' R' : [U' , R' D R]]",
    "WR": "[U R2 : [U' , R' D' R]]",
    "XR": "[R2 U : [R' U' R , D']]",
    "AS": "[D' U' : [R D R' , U2]]",
    "BS": "[D' : [U' , R D R']]",
    "DS": "[D : [R' D R , U']]",
    "ES": "[U D R' : [U' , R' D R]]",
    "FS": "[l U2 l' , F]",
    "GS": "[U D : [R U' R' , D]]",
    "HS": "",
    "IS": "[D R' D : [F2 , D' R D R']]",
    "KS": "[U : [R U' R' , D2]]",
    "LS": "[D' R D' : [R' U' R , D2]]",
    "NS": "[U' R' U' : [R D' R' , U2]]",
    "OS": "[U' : [R' U' R , D']]",
    "PS": "[U R' D' : [R U' R' , D']]",
    "QS": "[D R' U : [D , R U' R']]",
    "RS": "[U' R' U' : [R D' R' , U']]",
    "SS": "",
    "TS": "[D R' D : [F' , D' R D R']]",
    "US": "[U' D' R' D' : [R D R' , U']]",
    "VS": "[U' D' R' : [U , R' D R]]",
    "WS": "[U R2 : [U' , R' D2 R]]",
    "XS": "",
    "AT": "[D U' : [R D' R' , U2]]",
    "BT": "[D : [U' , R D' R']]",
    "DT": "[D' : [R' D' R , U']]",
    "ET": "[R U : [R' D' R , U]]",
    "FT": "[D' R' U' : [D' , R U R']]",
    "GT": "[R' D R : [D' , R U R']]",
    "HT": "[D2 : [R U R' , D]]",
    "IT": "[R U : [R' D' R , U2]]",
    "KT": "[R U R' U' : [D' , R U R']]",
    "LT": "[D : [R U R' , D2]]",
    "NT": "[R' F' R D' U : [R' D R , U2]]",
    "OT": "",
    "PT": "[R U R' , D']",
    "QT": "[R U' : [R' U R , D]]",
    "RT": "[D' R2' : [U , R D R']]",
    "ST": "[D2' R' : [F' , R D' R' D]]",
    "TT": "",
    "UT": "[D' R : [U' , R D' R']]",
    "VT": "[D' R D : [R' D' R , U]]",
    "WT": "",
    "XT": "[R U' D' : [R' U R , D2]]",
    "AU": "[R F' R' U' : [R D R' , U2]]",
    "BU": "[R F' : [R' U' R , D]]",
    "DU": "[R' U' R : [F2' , R' U R U']]",
    "EU": "[D' R : [R D' R' , U]]",
    "FU": "[U' R' U : [R U' R' , D]]",
    "GU": "",
    "HU": "[D R U' R' : [R' D R , U2]]",
    "IU": "[D' R : [R D' R' , U2]]",
    "KU": "[U R U' : [F2' , U R' U' R]]",
    "LU": "",
    "NU": "[U' R' : [R' D R , U2]]",
    "OU": "[U' R' : [R' D R , U]]",
    "PU": "[R D : [U , R' D' R]]",
    "QU": "[D' R U' : [R' U R , D']]",
    "RU": "[U' R' : [R' D R , U']]",
    "SU": "[U' D' R' D' : [U' , R D R']]",
    "TU": "[D' R : [R D' R' , U']]",
    "UU": " ",
    "VU": "[U' R' U R : [R U' R' , D]]",
    "WU": "[U' R2' : [D , R2 U R2' U' R2]]",
    "XU": "[R U' D' : [R' U R , D']]",
    "AV": "[R' D R U' R D' R' , U2]",
    "BV": "[R' D R U' R D' R' , U]",
    "DV": "[R' D R U' R D' R' , U']",
    "EV": "[U R' D' : [U' , R' D' R]]",
    "FV": "[U' D' R' U : [R U' R' , D]]",
    "GV": "[U D R D' : [U' , R' D R]]",
    "HV": "[R U' D R' : [R' D R , U2]]",
    "IV": "[R U' R' D' : [R' D R , U2]]",
    "KV": "",
    "LV": "[R U' R' : [R' D R , U2]]",
    "NV": "[D' U' R' : [R' D R , U2]]",
    "OV": "[D' U R U' : [F2 , U R' U' R]]",
    "PV": "",
    "QV": "[U R' U' : [R U R' , D']]",
    "RV": "[D' U' R' : [R' D R , U']]",
    "SV": "[U' D' R' : [R' D R , U]]",
    "TV": "[D' R D : [U , R' D' R]]",
    "UV": "[U' R' U R : [D , R U' R']]",
    "VV": "",
    "WV": "[D R U' R' : [D' , R' U R]]",
    "XV": "[R U' R' U' : [R D' R' , U2]]",
    "AW": "[R D' R' : [R' D R , U2]]",
    "BW": "[U' , R D' R' U R' D R]",
    "DW": "[R D' R' : [R' D R , U']]",
    "EW": "[D R : [R D' R', U]]",
    "FW": "[R U' R' : [D , R' U R]]",
    "GW": "[U R : [D , R U' R']]",
    "HW": "[R D' R' : [R' D R , U]]",
    "IW": "[D R : [R D' R' , U2]]",
    "KW": "[U R' D' : [U' , R' D R]]",
    "LW": "[D R : [R D' R' , U']]",
    "NW": "[U R U' D' : [R' D R , U2]]",
    "OW": "",
    "PW": "[D' R U' R' : [R' D R , U2]]",
    "QW": "[D R U' : [R' U R , D']]",
    "RW": "[U R : [D' , R U' R']]",
    "SW": "[U R : [D2 , R U' R']]",
    "TW": "",
    "UW": "",
    "VW": "[D R U' R' : [R' U R , D']]",
    "WW": "",
    "XW": "[R U' R' : [D' , R' U R]]",
    "AX": "[R' U' D' R : [R U' R' , D]]",
    "BX": "[R' B : [D' , R U R']]",
    "DX": "[R' D' R : [R U' R' , D]]",
    "EX": "[R : [R D' R' , U]]",
    "FX": "[U' D R' U : [R U' R' , D]]",
    "GX": "[D U R U' : [F2' , U R' U' R]]",
    "HX": "",
    "IX": "[R : [R D' R' , U2]]",
    "KX": "[R' D' R : [R U R' , D]]",
    "LX": "[D R D : [U , R' D' R]]",
    "NX": "[D U' R' : [R' D R , U2]]",
    "OX": "[U D' R D' : [U' , R' D R]]",
    "PX": "[R : [R D' R' , U']]",
    "QX": "[R U' : [R' U R , D']]",
    "RX": "[R2 U : [D' , R' U' R]]",
    "SX": "",
    "TX": "[R U' D : [R' U R , D2]]",
    "UX": "[R U' D2 : [R' U R , D]]",
    "VX": "[R U' R' U : [R D' R' , U2]]",
    "WX": "[R U' R' : [R' U R , D']]",
    "XX": ""
};
const CORNER_TYPES = {
    "AA": "",
    "BA": "U-Any / U-Any",
    "DA": "U-Any / U-Any",
    "EA": "",
    "FA": "U-Any / U-Any",
    "GA": "U-Top / D-Side",
    "HA": "U-Top / D-Side",
    "IA": "U-Any / U-Any",
    "KA": "U-Top / D-Side",
    "LA": "U-Top / D-Side",
    "NA": "U-Any / U-Any",
    "OA": "U-Top / D-Side",
    "PA": "U-Top / D-Side",
    "QA": "U-Any / U-Any",
    "RA": "",
    "SA": "U-Top / D-Side",
    "TA": "U-Top / D-Side",
    "UA": "U-Top / D-Bottom",
    "VA": "Special",
    "WA": "U-Top / D-Bottom",
    "XA": "Special",
    "AB": "U-Any / U-Any",
    "BB": "",
    "DB": "U-Any / U-Any",
    "EB": "U-Any / U-Any",
    "FB": "U-Any / U-Any",
    "GB": "U-Top / D-Side",
    "HB": "U-Top / D-Side",
    "IB": "U-Any / U-Any",
    "KB": "U-Top / D-Side",
    "LB": "U-Top / D-Side",
    "NB": "",
    "OB": "U-Top / D-Side",
    "PB": "U-Top / D-Side",
    "QB": "",
    "RB": "U-Any / U-Any",
    "SB": "U-Top / D-Side",
    "TB": "U-Top / D-Side",
    "UB": "U-Top / D-Bottom",
    "VB": "Special",
    "WB": "Special",
    "XB": "U-Top / D-Bottom",
    "AD": "U-Any / U-Any",
    "BD": "U-Any / U-Any",
    "DD": "",
    "ED": "U-Any / U-Any",
    "FD": "",
    "GD": "U-Top / D-Side",
    "HD": "U-Top / D-Side",
    "ID": "",
    "KD": "U-Top / D-Side",
    "LD": "U-Top / D-Side",
    "ND": "U-Any / U-Any",
    "OD": "U-Top / D-Side",
    "PD": "U-Top / D-Side",
    "QD": "U-Any / U-Any",
    "RD": "U-Any / U-Any",
    "SD": "U-Top / D-Side",
    "TD": "U-Top / D-Side",
    "UD": "Special",
    "VD": "Special",
    "WD": "U-Top / D-Bottom",
    "XD": "Special",
    "AE": "",
    "BE": "U-Any / U-Any",
    "DE": "U-Any / U-Any",
    "EE": "",
    "FE": "U-Any / U-Any",
    "GE": "U-Side / D-Any",
    "HE": "U-Side / D-Any",
    "IE": "U-Any / U-Any",
    "KE": "U-Side / D-Any",
    "LE": "U-Side / D-Any",
    "NE": "U-Any / U-Any",
    "OE": "Special",
    "PE": "U-Side / D-Any",
    "QE": "U-Any / U-Any",
    "RE": "",
    "SE": "U-Side / D-Any",
    "TE": "U-Side / D-Any",
    "UE": "U-Side / D-Any",
    "VE": "U-Side / D-Any",
    "WE": "U-Side / D-Any",
    "XE": "U-Side / D-Any",
    "AF": "U-Any / U-Any",
    "BF": "U-Any / U-Any",
    "DF": "",
    "EF": "U-Any / U-Any",
    "FF": "",
    "GF": "LUF / D-Any",
    "HF": "LUF / D-Any",
    "IF": "",
    "KF": "Special",
    "LF": "LUF / D-Any",
    "NF": "U-Any / U-Any",
    "OF": "Special",
    "PF": "LUF / D-Any",
    "QF": "U-Any / U-Any",
    "RF": "U-Any / U-Any",
    "SF": "Special",
    "TF": "LUF / D-Any",
    "UF": "LUF / D-Any",
    "VF": "LUF / D-Any",
    "WF": "Special",
    "XF": "LUF / D-Any",
    "AG": "U-Top / D-Side",
    "BG": "U-Top / D-Side",
    "DG": "U-Top / D-Side",
    "EG": "U-Side / D-Any",
    "FG": "LUF / D-Any",
    "GG": "",
    "HG": "Special",
    "IG": "Special",
    "KG": "D-Side / D-Side",
    "LG": "",
    "NG": "U-Side / D-Any",
    "OG": "D-Side / D-Side",
    "PG": "D-Side / D-Side",
    "QG": "BUR / D-Any",
    "RG": "Special",
    "SG": "D-Side / D-Side",
    "TG": "Special",
    "UG": "",
    "VG": "D-Side / D-Bottom",
    "WG": "D-Side / D-Bottom",
    "XG": "Special",
    "AH": "U-Top / D-Side",
    "BH": "U-Top / D-Side",
    "DH": "U-Top / D-Side",
    "EH": "U-Side / D-Any",
    "FH": "LUF / D-Any",
    "GH": "Special",
    "HH": "",
    "IH": "U-Side / D-Any",
    "KH": "D-Side / D-Side",
    "LH": "D-Side / D-Side",
    "NH": "U-Side / D-Any",
    "OH": "D-Side / D-Side",
    "PH": "D-Side / D-Side",
    "QH": "Special",
    "RH": "Special",
    "SH": "",
    "TH": "D-Side / D-Side",
    "UH": "Special",
    "VH": "Special",
    "WH": "Special",
    "XH": "",
    "AI": "U-Any / U-Any",
    "BI": "U-Any / U-Any",
    "DI": "",
    "EI": "U-Any / U-Any",
    "FI": "",
    "GI": "Special",
    "HI": "U-Side / D-Any",
    "II": "",
    "KI": "Special",
    "LI": "U-Side / D-Any",
    "NI": "U-Any / U-Any",
    "OI": "U-Side / D-Any",
    "PI": "U-Side / D-Any",
    "QI": "U-Any / U-Any",
    "RI": "U-Any / U-Any",
    "SI": "Special",
    "TI": "U-Side / D-Any",
    "UI": "U-Side / D-Any",
    "VI": "Special",
    "WI": "U-Side / D-Any",
    "XI": "U-Side / D-Any",
    "AK": "U-Top / D-Side",
    "BK": "U-Top / D-Side",
    "DK": "U-Top / D-Side",
    "EK": "U-Side / D-Any",
    "FK": "Special",
    "GK": "D-Side / D-Side",
    "HK": "D-Side / D-Side",
    "IK": "Special",
    "KK": "",
    "LK": "Special",
    "NK": "U-Side / D-Any",
    "OK": "D-Side / D-Side",
    "PK": "",
    "QK": "BUR / D-Any",
    "RK": "U-Side / D-Any",
    "SK": "D-Side / D-Side",
    "TK": "Special",
    "UK": "Special",
    "VK": "",
    "WK": "D-Side / D-Bottom",
    "XK": "Special",
    "AL": "U-Top / D-Side",
    "BL": "U-Top / D-Side",
    "DL": "U-Top / D-Side",
    "EL": "U-Side / D-Any",
    "FL": "LUF / D-Any",
    "GL": "",
    "HL": "D-Side / D-Side",
    "IL": "U-Side / D-Any",
    "KL": "Special",
    "LL": "",
    "NL": "U-Side / D-Any",
    "OL": "D-Side / D-Side",
    "PL": "D-Side / D-Side",
    "QL": "Special",
    "RL": "Special",
    "SL": "D-Side / D-Side",
    "TL": "D-Side / D-Side",
    "UL": "",
    "VL": "Special",
    "WL": "D-Side / D-Bottom",
    "XL": "D-Side / D-Bottom",
    "AN": "U-Any / U-Any",
    "BN": "",
    "DN": "U-Any / U-Any",
    "EN": "U-Any / U-Any",
    "FN": "U-Any / U-Any",
    "GN": "U-Side / D-Any",
    "HN": "U-Side / D-Any",
    "IN": "U-Any / U-Any",
    "KN": "U-Side / D-Any",
    "LN": "U-Side / D-Any",
    "NN": "",
    "ON": "U-Side / D-Any",
    "PN": "U-Side / D-Any",
    "QN": "",
    "RN": "U-Any / U-Any",
    "SN": "U-Side / D-Any",
    "TN": "Special",
    "UN": "U-Side / D-Any",
    "VN": "U-Side / D-Any",
    "WN": "U-Side / D-Any",
    "XN": "U-Side / D-Any",
    "AO": "U-Top / D-Side",
    "BO": "U-Top / D-Side",
    "DO": "U-Top / D-Side",
    "EO": "Special",
    "FO": "Special",
    "GO": "D-Side / D-Side",
    "HO": "D-Side / D-Side",
    "IO": "U-Side / D-Any",
    "KO": "D-Side / D-Side",
    "LO": "D-Side / D-Side",
    "NO": "U-Side / D-Any",
    "OO": "",
    "PO": "Special",
    "QO": "BUR / D-Any",
    "RO": "Special",
    "SO": "D-Side / D-Side",
    "TO": "",
    "UO": "D-Side / D-Bottom",
    "VO": "Special",
    "WO": "",
    "XO": "D-Side / D-Bottom",
    "AP": "U-Top / D-Side",
    "BP": "U-Top / D-Side",
    "DP": "U-Top / D-Side",
    "EP": "U-Side / D-Any",
    "FP": "LUF / D-Any",
    "GP": "D-Side / D-Side",
    "HP": "D-Side / D-Side",
    "IP": "U-Side / D-Any",
    "KP": "",
    "LP": "D-Side / D-Side",
    "NP": "U-Side / D-Any",
    "OP": "D-Side / D-Side",
    "PP": "",
    "QP": "BUR / D-Any",
    "RP": "Special",
    "SP": "D-Side / D-Side",
    "TP": "D-Side / D-Side",
    "UP": "D-Side / D-Bottom",
    "VP": "",
    "WP": "Special",
    "XP": "D-Side / D-Bottom",
    "AQ": "U-Any / U-Any",
    "BQ": "",
    "DQ": "U-Any / U-Any",
    "EQ": "U-Any / U-Any",
    "FQ": "U-Any / U-Any",
    "GQ": "BUR / D-Any",
    "HQ": "Special",
    "IQ": "U-Any / U-Any",
    "KQ": "BUR / D-Any",
    "LQ": "Special",
    "NQ": "",
    "OQ": "BUR / D-Any",
    "PQ": "BUR / D-Any",
    "QQ": "",
    "RQ": "U-Any / U-Any",
    "SQ": "BUR / D-Any",
    "TQ": "Special",
    "UQ": "BUR / D-Any",
    "VQ": "Special",
    "WQ": "BUR / D-Any",
    "XQ": "BUR / D-Any",
    "AR": "",
    "BR": "U-Any / U-Any",
    "DR": "U-Any / U-Any",
    "ER": "",
    "FR": "U-Any / U-Any",
    "GR": "Special",
    "HR": "Special",
    "IR": "U-Any / U-Any",
    "KR": "U-Side / D-Any",
    "LR": "Special",
    "NR": "U-Any / U-Any",
    "OR": "Special",
    "PR": "Special",
    "QR": "U-Any / U-Any",
    "RR": "",
    "SR": "U-Side / D-Any",
    "TR": "Special",
    "UR": "U-Side / D-Any",
    "VR": "U-Side / D-Any",
    "WR": "Special",
    "XR": "Special",
    "AS": "U-Top / D-Side",
    "BS": "U-Top / D-Side",
    "DS": "U-Top / D-Side",
    "ES": "U-Side / D-Any",
    "FS": "Special",
    "GS": "D-Side / D-Side",
    "HS": "",
    "IS": "Special",
    "KS": "D-Side / D-Side",
    "LS": "D-Side / D-Side",
    "NS": "U-Side / D-Any",
    "OS": "D-Side / D-Side",
    "PS": "D-Side / D-Side",
    "QS": "BUR / D-Any",
    "RS": "U-Side / D-Any",
    "SS": "",
    "TS": "Special",
    "US": "D-Side / D-Bottom",
    "VS": "D-Side / D-Bottom",
    "WS": "D-Side / D-Bottom",
    "XS": "",
    "AT": "U-Top / D-Side",
    "BT": "U-Top / D-Side",
    "DT": "U-Top / D-Side",
    "ET": "U-Side / D-Any",
    "FT": "LUF / D-Any",
    "GT": "Special",
    "HT": "D-Side / D-Side",
    "IT": "U-Side / D-Any",
    "KT": "Special",
    "LT": "D-Side / D-Side",
    "NT": "Special",
    "OT": "",
    "PT": "D-Side / D-Side",
    "QT": "Special",
    "RT": "Special",
    "ST": "Special",
    "TT": "",
    "UT": "D-Side / D-Bottom",
    "VT": "D-Side / D-Bottom",
    "WT": "",
    "XT": "D-Side / D-Bottom",
    "AU": "U-Top / D-Bottom",
    "BU": "U-Top / D-Bottom",
    "DU": "Special",
    "EU": "U-Side / D-Any",
    "FU": "LUF / D-Any",
    "GU": "",
    "HU": "Special",
    "IU": "U-Side / D-Any",
    "KU": "Special",
    "LU": "",
    "NU": "U-Side / D-Any",
    "OU": "D-Side / D-Bottom",
    "PU": "D-Side / D-Bottom",
    "QU": "BUR / D-Any",
    "RU": "U-Side / D-Any",
    "SU": "D-Side / D-Bottom",
    "TU": "D-Side / D-Bottom",
    "UU": " ",
    "VU": "D-Bottom / D-Bottom",
    "WU": "D-Bottom / D-Bottom",
    "XU": "D-Bottom / D-Bottom",
    "AV": "Special",
    "BV": "Special",
    "DV": "Special",
    "EV": "U-Side / D-Any",
    "FV": "LUF / D-Any",
    "GV": "D-Side / D-Bottom",
    "HV": "Special",
    "IV": "Special",
    "KV": "",
    "LV": "Special",
    "NV": "U-Side / D-Any",
    "OV": "Special",
    "PV": "",
    "QV": "Special",
    "RV": "U-Side / D-Any",
    "SV": "D-Side / D-Bottom",
    "TV": "D-Side / D-Bottom",
    "UV": "D-Bottom / D-Bottom",
    "VV": "",
    "WV": "D-Bottom / D-Bottom",
    "XV": "D-Bottom / D-Bottom",
    "AW": "U-Top / D-Bottom",
    "BW": "Special",
    "DW": "U-Top / D-Bottom",
    "EW": "U-Side / D-Any",
    "FW": "Special",
    "GW": "D-Side / D-Bottom",
    "HW": "Special",
    "IW": "U-Side / D-Any",
    "KW": "D-Side / D-Bottom",
    "LW": "D-Side / D-Bottom",
    "NW": "U-Side / D-Any",
    "OW": "",
    "PW": "Special",
    "QW": "BUR / D-Any",
    "RW": "Special",
    "SW": "D-Side / D-Bottom",
    "TW": "",
    "UW": "",
    "VW": "D-Bottom / D-Bottom",
    "WW": "",
    "XW": "D-Bottom / D-Bottom",
    "AX": "Special",
    "BX": "U-Top / D-Bottom",
    "DX": "Special",
    "EX": "U-Side / D-Any",
    "FX": "LUF / D-Any",
    "GX": "Special",
    "HX": "",
    "IX": "U-Side / D-Any",
    "KX": "Special",
    "LX": "D-Side / D-Bottom",
    "NX": "U-Side / D-Any",
    "OX": "D-Side / D-Bottom",
    "PX": "D-Side / D-Bottom",
    "QX": "BUR / D-Any",
    "RX": "Special",
    "SX": "",
    "TX": "D-Side / D-Bottom",
    "UX": "D-Bottom / D-Bottom",
    "VX": "D-Bottom / D-Bottom",
    "WX": "D-Bottom / D-Bottom",
    "XX": ""
};
